name: Deploy to Heroku

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku git:remote -a rollback-heroku
          git push heroku main

  rollback:
    runs-on: ubuntu-latest
    needs: deploy # Only trigger rollback after deploy job
    if: github.event.inputs.rollback == 'true' # Manual rollback trigger

    steps:
      - name: Set up Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Rollback Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku releases:rollback -a rollback-heroku

  alert_rollback:
    runs-on: ubuntu-latest
    if: failure() # Automatic rollback on failure

    steps:
      - name: Set up Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Automatic Rollback Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku releases:rollback -a rollback-heroku
